### ISSUE TITLE
Mortgage Calculator doesn't update sometimes

### ISSUE THREAD

**Issue by internationalhouseofdonald** [internationalhouseofdonald/srep#8]

**Comment by internationalhouseofdonald** [comment]
This is sort of like [this issue](https://github.com/internationalhouseofdonald/srep/issues/6). If it bothers you, just reload the listing from the Search Results. It has to do with the data not being set within a React component lifecycle hook somewhere.

**Comment by imgnx** [comment]
Parsing issue.
